name: Android

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create local.properties
        run: |
          touch local.properties
          echo "API_KEY=" >> local.properties

      - name: Run Unit Test
        run: ./gradlew testDebugUnitTest